(test
 (name ocaat_test)
 (modules ocaat_test)
 (libraries ocaat))

(test
 (name markdown_test)
 (modules markdown_test)
 (libraries cmarkit ocaat))

(test
 (name cli_fixture_test)
 (modules cli_fixture cli_fixture_test)
 (deps ../bin/main.exe)
 (libraries cmarkit ocaat cohttp-lwt-unix lwt.unix unix yojson))

(test
 (name identity_test)
 (modules cli_fixture identity_test)
 (deps ../bin/main.exe)
 (libraries cmarkit ocaat cohttp-lwt-unix lwt.unix unix yojson))

(test
 (name record_plc_test)
 (modules cli_fixture record_plc_test)
 (deps ../bin/main.exe)
 (libraries ocaat cohttp-lwt-unix lwt.unix unix yojson))

(test
 (name lexicon_test)
 (modules cli_fixture lexicon_test)
 (deps ../bin/main.exe)
 (libraries ocaat cohttp-lwt-unix lwt.unix unix yojson))

(test
 (name resource_test)
 (modules cli_fixture resource_test)
 (deps ../bin/main.exe)
 (libraries ocaat cohttp-lwt-unix lwt.unix unix yojson))
